Feat : Users 등록,조회,수정 구현
DB 및 postman 테스트까지 완료

에러 해결
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.USERS(ID) ( /* key:2 */ CAST(2 AS BIGINT), 'Spring')"; SQL statement:
insert into users (name,id) values (?,default) [23505-224]

  에러원인 : JpaRepo<> 안에 키밸류값이 뒤바뀌어있었음.
             엔티티객체, id객체(Long)이여야함

에러 해결
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository' defined in

  에러원인 : JpaRepo를 상속하면 자동으로 @Repository가 추가되는데 여기에
  또 interface UserRepository에 @Repo를 추가해서 발생한 것